### Teste da raiz da aplicação
GET http://localhost:5094/
Content-Type: application/json

###

### Cadastrar um produto
POST http://localhost:5094/api/produto/cadastrar
Content-Type: application/json

{
    "nome": "Produto 2",
    "preco": 25.50
}

###

### Listar todos os produtos
GET http://localhost:5094/api/produto/listar
Content-Type: application/json
